import type { EventRecord, Speaker, StoreData, TicketSignup, Venue, Volunteer } from '@/lib/models'

const now = '2026-09-18T15:00:00.000Z'

const venues: Venue[] = [
  {
    id: 'venue-4mlk',
    year: '2027',
    name: '4MLK',
    neighborhood: '4MLK / Westside',
    address: '4 N. Martin Luther King Jr. Blvd, Baltimore, MD 21201',
    capacity: 120,
    availableDates: ['2027-04-26', '2027-04-27', '2027-04-28', '2027-04-29', '2027-04-30'],
    venueType: 'hybrid',
    costType: 'Free',
    costAmount: null,
    amenities: ['AV', 'Seating', 'WiFi', 'Projector', 'Microphone', 'Stage', 'Accessible'],
    contactName: '4MLK Host Team',
    contactEmail: 'host@4mlk.com',
    status: 'reviewed',
    createdAt: now,
  },
  {
    id: 'venue-harbor-loft',
    year: '2027',
    name: 'Harbor Loft Studio',
    neighborhood: 'Harbor East',
    address: '1000 Lancaster St, Baltimore, MD 21202',
    capacity: 60,
    availableDates: ['2027-04-26', '2027-04-27', '2027-04-29'],
    venueType: 'tech',
    costType: 'Low-Cost',
    costAmount: 250,
    amenities: ['AV', 'Seating', 'WiFi', 'Projector', 'Microphone', 'Accessible'],
    contactName: 'Maya Chen',
    contactEmail: 'maya@harborloft.example',
    status: 'pending',
    createdAt: now,
  },
  {
    id: 'venue-fells-room',
    year: '2027',
    name: 'The Fells Room',
    neighborhood: 'Fells Point',
    address: '1626 Thames St, Baltimore, MD 21231',
    capacity: 80,
    availableDates: ['2027-04-27', '2027-04-28', '2027-04-30'],
    venueType: 'social',
    costType: 'Standard',
    costAmount: 600,
    amenities: ['AV', 'Seating', 'Bar', 'WiFi', 'Microphone', 'Accessible'],
    contactName: 'Andre Walsh',
    contactEmail: 'andre@fellsroom.example',
    status: 'reviewed',
    createdAt: now,
  },
  {
    id: 'venue-station-north',
    year: '2027',
    name: 'Station North Workshop',
    neighborhood: 'Station North',
    address: '10 E North Ave, Baltimore, MD 21202',
    capacity: 36,
    availableDates: ['2027-04-28', '2027-04-29', '2027-04-30'],
    venueType: 'tech',
    costType: 'Free',
    costAmount: null,
    amenities: ['Seating', 'WiFi', 'Projector', 'Accessible'],
    contactName: 'Priya Shah',
    contactEmail: 'priya@stationnorth.example',
    status: 'pending',
    createdAt: now,
  },
]

const speakers: Speaker[] = [
  {
    id: 'speaker-ada',
    year: '2027',
    name: 'Ada Okonkwo',
    email: 'ada@example.com',
    talkTitle: 'Shipping in Charm City',
    talkDescription:
      'A fireside on what it takes to ship product from Baltimore. Talent, customers, and the rooms where deals actually happen after dark.',
    topic: 'Startup',
    format: 'fireside',
    preferredNeighborhood: 'Harbor East',
    preferredDate: '2027-04-26',
    linkedinUrl: 'https://www.linkedin.com/',
    websiteUrl: '',
    portfolioUrl: '',
    status: 'reviewed',
    createdAt: now,
  },
  {
    id: 'speaker-jamal',
    year: '2027',
    name: 'Jamal Reed',
    email: 'jamal@example.com',
    talkTitle: 'Cyber After Dark',
    talkDescription:
      'A panel of Baltimore defenders on the threats hitting local hospitals, ports, and startups, and the people already on the night shift.',
    topic: 'Cyber',
    format: 'panel',
    preferredNeighborhood: 'Downtown',
    preferredDate: '2027-04-27',
    linkedinUrl: 'https://www.linkedin.com/',
    websiteUrl: '',
    portfolioUrl: '',
    status: 'reviewed',
    createdAt: now,
  },
  {
    id: 'speaker-lena',
    year: '2027',
    name: 'Lena Park',
    email: 'lena@example.com',
    talkTitle: 'Founder Night',
    talkDescription:
      'A social talk for operators who want peers, not pitches. Bring a story from the last thing you shipped.',
    topic: 'Community',
    format: 'social talk',
    preferredNeighborhood: 'Fells Point',
    preferredDate: '2027-04-28',
    linkedinUrl: '',
    websiteUrl: '',
    portfolioUrl: '',
    status: 'reviewed',
    createdAt: now,
  },
  {
    id: 'speaker-nico',
    year: '2027',
    name: 'Nico Alvarez',
    email: 'nico@example.com',
    talkTitle: 'Agents in the Warehouse',
    talkDescription:
      'A workshop on putting AI agents next to real Baltimore logistics data without lighting the building on fire.',
    topic: 'AI',
    format: 'workshop',
    preferredNeighborhood: 'Any',
    preferredDate: '2027-04-29',
    linkedinUrl: 'https://www.linkedin.com/',
    websiteUrl: 'https://example.com',
    portfolioUrl: '',
    status: 'pending',
    createdAt: now,
  },
  {
    id: 'speaker-renee',
    year: '2027',
    name: 'Renée Brooks',
    email: 'renee@example.com',
    talkTitle: 'Product Taste After 6',
    talkDescription:
      'Why Charm City products feel different, and how to keep that taste when the user base grows past the block.',
    topic: 'Product',
    format: 'fireside',
    preferredNeighborhood: 'Mount Vernon',
    preferredDate: 'Any',
    linkedinUrl: '',
    websiteUrl: '',
    portfolioUrl: '',
    status: 'pending',
    createdAt: now,
  },
]

const events: EventRecord[] = [
  {
    id: 'event-shipping',
    year: '2027',
    slug: 'shipping-in-charm-city',
    name: 'Shipping in Charm City',
    description:
      'A fireside on what it takes to ship product from Baltimore. Talent, customers, and the rooms where deals actually happen after dark.',
    venueId: 'venue-4mlk',
    speakerId: 'speaker-ada',
    date: '2027-04-26',
    time: '6:30 PM – 8:00 PM',
    neighborhood: '4MLK / Westside',
    topic: 'Startup',
    format: 'fireside',
    status: 'draft',
    matchScore: 80,
    matchReasons: ['Date matches venue availability', 'Topic (Startup) fits a hybrid room'],
    createdAt: now,
    publishedAt: null,
  },
  {
    id: 'event-cyber',
    year: '2027',
    slug: 'cyber-after-dark',
    name: 'Cyber After Dark',
    description:
      'A panel of Baltimore defenders on the threats hitting local hospitals, ports, and startups, and the people already on the night shift.',
    venueId: 'venue-4mlk',
    speakerId: 'speaker-jamal',
    date: '2027-04-27',
    time: '7:00 PM – 8:30 PM',
    neighborhood: '4MLK / Westside',
    topic: 'Cyber',
    format: 'panel',
    status: 'draft',
    matchScore: 75,
    matchReasons: ['Date matches venue availability', 'AV supports this talk format'],
    createdAt: now,
    publishedAt: null,
  },
  {
    id: 'event-founder-night',
    year: '2027',
    slug: 'founder-night',
    name: 'Founder Night',
    description:
      'A social talk for operators who want peers, not pitches. Bring a story from the last thing you shipped.',
    venueId: 'venue-fells-room',
    speakerId: 'speaker-lena',
    date: '2027-04-28',
    time: '8:00 PM – 10:00 PM',
    neighborhood: 'Fells Point',
    topic: 'Community',
    format: 'social talk',
    status: 'draft',
    matchScore: 100,
    matchReasons: [
      'Date matches venue availability',
      'Neighborhood match',
      'Topic (Community) fits a social room',
      'Layout fits a social talk',
    ],
    createdAt: now,
    publishedAt: null,
  },
]

const volunteers: Volunteer[] = []
const ticketSignups: TicketSignup[] = []

export const SEED_STORE: StoreData = { venues, speakers, events, volunteers, ticketSignups }
